---
name: Check
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install linter
        uses: golangci/golangci-lint-action@v8
      - name: Lint
        run: golangci-lint run ./...
  vet:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Vet
        run: go vet ./...
