---
name: Lint and Test
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    strategy:
      matrix:
        go-version: ["1.24"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install linter
        uses: golangci/golangci-lint-action@v8
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Lint
        run: golangci-lint run ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
