---
name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        run: go test ./...
